### ISSUE TITLE
How different/difficult would it be to use this for running Linux on the hi8?

### ISSUE THREAD

**Issue by djvdorp** [Manouchehri/vi8#7]
Hi8 specs (mine): http://www.gearbest.com/tablet-pcs/pp_219480.html
Vi8 specs (yours): http://www.gearbest.com/tablet-pcs/pp_187771.html

**Comment by Manouchehri** [comment]
It really depends on the exact controllers inside of it. It could be easier
or harder.

If you share some system information that would probably help. Boot up a
Live USB and post dmesg, lsusb and lspci.

**Comment by djvdorp** [comment]
Thanks @Manouchehri -- will try to do that as soon as I get a Linux Live USB booting on it.
I also started my own repo (inspired by yours) to get more information and resources into the open about the hi8, can be found here: https://github.com/djvdorp/hi8

**Comment by sigboe** [comment]
Closing this issue since its better to have the discussion on the other github repo, will add @djvdorp link to our readme, feel free to do the same. And remember you can use a lot of the information from our repo for your work, if you see something I have done before you can open an issue about it on your repo and tag me I will try to answer.
